---
title: "AN6003 Project"
author: "Jiang Yifan"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(dirname(rstudioapi::getActiveDocumentContext()$path))
```

```{r}
library(caTools)
library(data.table)
library(caret)
library(rpart)
library(rpart.plot)
library(e1071)
library(randomForest)
library(neuralnet)
```

```{r}
cols <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "num")
```

```{r}
df <- read.table("processed.cleveland.data", sep = ",", col.names=cols, na.strings = c("?"))
```

```{r}
df$ca[which(is.na(df$ca))] <- 2
df$thal[which(is.na(df$thal))] <- 3
df$num[df$num > 1] <- 1
```

```{r}
for (i in c(2, 3, 6, 7, 9, 11, 12, 13, 14)) {
  df[, i] <- factor(df[, i])
}
```

## Train and test
```{r}
set.seed(2022) 
split <- sample.split(df$num)
trainSet <- subset(df, split == TRUE)
testSet <- subset(df, split == FALSE)
```

## Scaling
```{r}
# trainSet[, c(1, 4, 5, 8, 10)] <- scale(trainSet[, c(1, 4, 5, 8, 10)])
# testSet[, c(1, 4, 5, 8, 10)] <- scale(testSet[, c(1, 4, 5, 8, 10)])
```

## Logistic Regression
```{r}
m.logistic <- glm(num ~ ., family = binomial, data = trainSet)
```

```{r}
prob <- predict(m.logistic, testSet, type = "response")
threshold <- 0.5
num.logistic <- ifelse(prob > threshold, 1, 0)
confusionMatrix(testSet$num, factor(num.logistic))
```

## CART Tree
```{r}
getOptCp <- function(m) {
  CVerror.cap <-
    m$cptable[which.min(m$cptable[, "xerror"]), "xerror"] +
    m$cptable[which.min(m$cptable[, "xerror"]), "xstd"]
  i <- 1
  j <- 4
  while (m$cptable[i, j] > CVerror.cap) {
    i <- i + 1
  }
  ifelse(i > 1, sqrt(m$cptable[i, 1] * m$cptable[i - 1, 1]), 1)
}
```

```{r}
m1.cart <- rpart(num ~ ., data = trainSet, method = "class", cp = 0)
cp.opt <- getOptCp(m1.cart)
m.cart <- prune(m1.cart, cp = cp.opt)
m.cart.rules <- rpart.rules(m.cart, nn = T, cover = T)
View(m.cart.rules)
```

```{r}
num.cart <- predict(m.cart, type = "class", newdata = testSet)
confusionMatrix(testSet$num, factor(num.cart))
```

## Random Forest
```{r}
m.rf <- randomForest(num ~ .,
                     data = trainSet,
                     importance = T)

num.rf <- predict(m.rf, newdata = testSet)
confusionMatrix(testSet$num, factor(num.rf))
```

## SVM
```{r}
m.svm <- svm(num ~ .,
             data = trainSet)
num.svm <- predict(m.svm, newdata = testSet)
confusionMatrix(testSet$num, factor(num.svm))
```
# NN
```{r}
df1 <- copy(df)
```

```{r}
for (i in c(2, 6, 9)) {
  df1[, i] <- as.numeric(df1[, i])
}
```

```{r}
dummy_cp <- model.matrix(~cp, df1)
colnames(dummy_cp)[1] <- "cp1"

dummy_restecg <- model.matrix(~restecg, df1)
colnames(dummy_restecg)[1] <- "restecg1"

dummy_slope <- model.matrix(~slope, df1)
colnames(dummy_slope)[1] <- "slope1"

dummy_ca <- model.matrix(~ca, df1)
colnames(dummy_ca)[1] <- "ca1"

dummy_thal <- model.matrix(~thal, df1)
colnames(dummy_thal)[1] <- "thal1"
```

```{r}
df1 <- cbind(df1[, -c(3, 7, 11, 12, 13)], dummy_cp, dummy_restecg, dummy_slope, dummy_ca, dummy_thal)
```

```{r}
set.seed(2022) 
split1 <- sample.split(df1$num)
trainSet1 <- subset(df1, split1 == TRUE)
testSet1 <- subset(df1, split1 == FALSE)
```

```{r}
set.seed(2000) 
m.nn <- neuralnet(num == 1 ~.,
                  data = trainSet1, hidden = 3, linear.output = FALSE)
```

```{r}
num.nn <- predict(m.nn, newdata = testSet1)
```

```{r}
confusionMatrix(testSet1$num, factor(round(num.nn)))
```

```{r}
plot(m.nn)
```

